import SportsIcon from '../assets/icons/nav/sports.svg';
import SportsActiveIcon from '../assets/icons/nav/sports-active.svg';
import CasinoIcon from '../assets/icons/nav/casino.svg';
import CasinoActiveIcon from '../assets/icons/nav/casino-active.svg';
import EsportsIcon from '../assets/icons/nav/esports.svg';
import EsportsActiveIcon from '../assets/icons/nav/esports-active.svg';
import PromotionIcon from '../assets/icons/nav/promotion.svg';
import PromotionActiveIcon from '../assets/icons/nav/promotion-active.svg';

export const navitemList = [
    {
        key: 1,
        text: "Sports",
        icon: SportsIcon,
        activeIcon: SportsActiveIcon,
        path: "/sports",
        children: [
            {
                key: 101,
                text: "Home",
                path: "/",
            },
            {
                key: 102,
                text: "My Bets",
                action: "mybets"
            },
            {
                key: 103,
                text: "In Play",
                path: "/live",
            },
            {
                key: 104,
                text: "Popular",
                header: true,
            },
            {
                key: 105,
                text: "Soccer",
                icon: '/imgs/sports/soccer.svg',
                activeIcon: '/imgs/sports/soccer-active.svg',
                path: "/soccer",
                favoritable: true,
            },
            {
                key: 106,
                text: "Tennis",
                icon: '/imgs/sports/tennis.svg',
                activeIcon: '/imgs/sports/tennis-active.svg',
                path: "/tennis",
                favoritable: true,
            },
            {
                key: 107,
                text: "American Football",
                icon: '/imgs/sports/american football.svg',
                activeIcon: '/imgs/sports/american football-active.svg',
                path: "/american-football",
                favoritable: true,
            },
            {
                key: 108,
                text: "Basketball",
                icon: '/imgs/sports/basketball.svg',
                activeIcon: '/imgs/sports/basketball-active.svg',
                path: "/basketball",
                favoritable: true,
            },
            {
                key: 109,
                text: "Baseball",
                icon: '/imgs/sports/baseball.svg',
                activeIcon: '/imgs/sports/baseball-active.svg',
                path: "/baseball",
                favoritable: true,
            },
            {
                key: 110,
                text: "MMA",
                icon: '/imgs/sports/mixed martial arts.svg',
                activeIcon: '/imgs/sports/mixed martial arts-active.svg',
                path: "/mma",
                favoritable: true,
            },
            {
                key: 111,
                text: "All Sports",
                header: true,
            },
            {
                key: 112,
                text: "Aussie Rules",
                icon: '/imgs/sports/aussie rules.svg',
                activeIcon: '/imgs/sports/aussie rules-active.svg',
                path: "/aussie-rules",
                favoritable: true,
            },
            {
                key: 113,
                text: "Badminton",
                icon: '/imgs/sports/badminton.svg',
                activeIcon: '/imgs/sports/badminton-active.svg',
                path: "/badminton",
                favoritable: true,
            },
            {
                key: 114,
                text: "Bandy",
                icon: '/imgs/sports/bandy.svg',
                activeIcon: '/imgs/sports/bandy-active.svg',
                path: "/bandy",
                favoritable: true,
            },
            {
                key: 115,
                text: "Boxing",
                icon: '/imgs/sports/boxing.svg',
                activeIcon: '/imgs/sports/boxing-active.svg',
                path: "/boxing",
                favoritable: true,
            },
            {
                key: 116,
                text: "Cricket",
                icon: '/imgs/sports/cricket.svg',
                activeIcon: '/imgs/sports/cricket-active.svg',
                path: "/cricket",
                favoritable: true,
            },
            {
                key: 117,
                text: "Darts",
                icon: '/imgs/sports/darts.svg',
                activeIcon: '/imgs/sports/darts-active.svg',
                path: "/darts",
                favoritable: true,
            },
            {
                key: 118,
                text: "FIFA",
                icon: '/imgs/sports/fifa.svg',
                activeIcon: '/imgs/sports/fifa-active.svg',
                path: "/fifa",
                favoritable: true,
            },
            {
                key: 119,
                text: "Floorball",
                icon: '/imgs/sports/floorball.svg',
                activeIcon: '/imgs/sports/floorball-active.svg',
                path: "/floorball",
                favoritable: true,
            },
            {
                key: 120,
                text: "Golf",
                icon: '/imgs/sports/golf.svg',
                activeIcon: '/imgs/sports/golf-active.svg',
                path: "/golf",
                favoritable: true,
            },
            {
                key: 121,
                text: "Greyhounds",
                icon: '/imgs/sports/greyhounds.svg',
                activeIcon: '/imgs/sports/greyhounds-active.svg',
                path: "/greyhounds",
                favoritable: true,
            },
            {
                key: 122,
                text: "Handball",
                icon: '/imgs/sports/handball.svg',
                activeIcon: '/imgs/sports/handball-active.svg',
                path: "/handball",
                favoritable: true,
            },
            {
                key: 123,
                text: "Horse Racing",
                icon: '/imgs/sports/horse racing.svg',
                activeIcon: '/imgs/sports/horse racing-active.svg',
                path: "/horse-racing",
                favoritable: true,
            },
            {
                key: 124,
                text: "Ice Hockey",
                icon: '/imgs/sports/ice hockey.svg',
                activeIcon: '/imgs/sports/ice hockey-active.svg',
                path: "/ice-hockey",
                favoritable: true,
            },
            {
                key: 125,
                text: "Politics",
                icon: '/imgs/sports/politics.svg',
                activeIcon: '/imgs/sports/politics-active.svg',
                path: "/politics",
                favoritable: true,
            },
            {
                key: 126,
                text: "Rugby League",
                icon: '/imgs/sports/rugby league.svg',
                activeIcon: '/imgs/sports/rugby league-active.svg',
                path: "/rugby-league",
                favoritable: true,
            },
            {
                key: 127,
                text: "Rugby Union",
                icon: '/imgs/sports/rugby union.svg',
                activeIcon: '/imgs/sports/rugby union-active.svg',
                path: "/rugby-union",
                favoritable: true,
            },
            {
                key: 128,
                text: "Snooker",
                icon: '/imgs/sports/snooker.svg',
                activeIcon: '/imgs/sports/snooker-active.svg',
                path: "/snooker",
                favoritable: true,
            },
            {
                key: 129,
                text: "Table Tennis",
                icon: '/imgs/sports/table tennis.svg',
                activeIcon: '/imgs/sports/table tennis-active.svg',
                path: "/table-tennis",
                favoritable: true,
            },
            {
                key: 130,
                text: "Volleyball",
                icon: '/imgs/sports/volleyball.svg',
                activeIcon: '/imgs/sports/volleyball-active.svg',
                path: "/volleyball",
                favoritable: true,
            },
        ],
    },
    {
        key: 2,
        text: "Casino",
        icon: CasinoIcon,
        activeIcon: CasinoActiveIcon,
        path: "/casino",
        children: [
            {
                key: 201,
                text: "Lobby",
                path: "/",
            },
            {
                key: 202,
                text: "Recently played",
                path: "/recent",
                badge: 10,
            },
            {
                key: 203,
                text: "Games",
                header: true,
            },
            {
                key: 204,
                text: "All games",
                path: "/",
            },
            {
                key: 205,
                text: "High Roller",
                path: "/high_roller_games",
            },
            {
                key: 206,
                text: "New Games",
                path: "/new_releases",
            },
            {
                key: 207,
                text: "Blackjack",
                path: "/blackjack",
            },
            {
                key: 208,
                text: "Crash",
                path: "/crash",
            },
            {
                key: 209,
                text: "Roulette",
                path: "/roulette",
            },
            {
                key: 210,
                text: "Baccarat",
                path: "/baccarat",
            },
            {
                key: 211,
                text: "Slots",
                path: "/slots",
            },
            {
                key: 212,
                text: "Game Shows",
                path: "/game_shows",
            },
            {
                key: 213,
                text: "Arcade",
                path: "/arcade",
            },
            {
                key: 214,
                text: "Table Games",
                path: "/table_games",
            },
            {
                key: 215,
                text: "Jackpot Slots",
                path: "/jackpot_slots",
            },
            {
                key: 216,
                text: "Instant Win",
                path: "/instant_win",
            },
            {
                key: 217,
                text: "Bingo and Keno",
                path: "/bingo",
            },
            {
                key: 218,
                text: "Video Poker",
                path: "/video_poker",
            },
            {
                key: 219,
                text: "Live Casino",
                header: true,
            },
            {
                key: 220,
                text: "Live dealer",
                path: "/live_dealer",
            },
            {
                key: 221,
                text: "Live Blackjack",
                path: "/live_blackjack",
            },
            {
                key: 222,
                text: "Live Roulette",
                path: "/live_roulette",
            },
            {
                key: 223,
                text: "Live Baccarat",
                path: "/live_baccarat",
            },
            {
                key: 224,
                text: "Live Game Shows",
                path: "/live_game_shows",
            },
            {
                key: 225,
                text: "Live High Roller Games",
                path: "/live_high_roller_games",
            },
            {
                key: 226,
                text: "Live Table Games",
                path: "/live_table_games",
            },
        ],
    },
    {
        key: 3,
        text: "Esports",
        icon: EsportsIcon,
        activeIcon: EsportsActiveIcon,
        path: "/esports",
        children: [
            {
                key: 301,
                text: "Home",
                path: "/",
            },
            {
                key: 302,
                text: "My Bets",
                action: "mybets"
            },
            {
                key: 303,
                text: "In Play",
                path: "/live",
            },
            {
                key: 304,
                text: "All Esports",
                header: true,
            },
            {
                key: 305,
                text: "Call of Duty",
                icon: '/imgs/esports/cod.svg',
                activeIcon: '/imgs/esports/cod-active.svg',
                path: "/call_of_duty",
                favoritable: true,
            },
            {
                key: 306,
                text: "Counter Strike",
                icon: '/imgs/esports/cs.svg',
                activeIcon: '/imgs/esports/cs.svg',
                path: "/counter_strike",
                favoritable: true,
            },
            {
                key: 307,
                text: "Dota 2",
                icon: '/imgs/esports/dota2.svg',
                activeIcon: '/imgs/esports/dota2.svg',
                path: "/dota2",
                favoritable: true,
            },
            {
                key: 309,
                text: "FIFA",
                icon: '/imgs/esports/fifa.svg',
                activeIcon: '/imgs/esports/fifa.svg',
                path: "/fifa",
                favoritable: true,
            },
            {
                key: 310,
                text: "Valorant",
                icon: '/imgs/esports/valorant.svg',
                activeIcon: '/imgs/esports/valorant.svg',
                path: "/valorant",
                favoritable: true,
            },
            {
                key: 311,
                text: "League Of Legends",
                icon: '/imgs/esports/lol.svg',
                activeIcon: '/imgs/esports/lol.svg',
                path: "/lol",
                favoritable: true,
            },
            {
                key: 312,
                text: "Starcraft",
                icon: '/imgs/esports/starcraft.svg',
                activeIcon: '/imgs/esports/starcraft.svg',
                path: "/starcraft",
                favoritable: true,
            },
            {
                key: 313,
                text: "",
                header: true,
            },
            {
                key: 314,
                text: "Discord",
            },
        ],
    },
    {
        key: 4,
        text: "Promos",
        icon: PromotionIcon,
        activeIcon: PromotionActiveIcon,
        path: "/promotions",
        children: [],
    },
];

export const networks = [
    { chain_id: 1, name: "Ethereum", currency: "ETH", base: "eth" },
    { chain_id: 56, name: "BNB Smart Chain", currency: "BNB", base: "eth" },
    // { chain_id: 43114, name: "Avalanche C-Chain", currency: "AVAX", base: "eth" },
    { chain_id: 137, name: "Polygon", currency: "MATIC", base: "eth" },
    { chain_id: 900, name: "Solana", currency: "SOL", base: "solana" },
    { chain_id: 1000, name: "Tron", currency: "TRX", base: "tron" },
    { chain_id: 1100, name: "TON", currency: "TON", base: "ton" },
    { chain_id: 8453, name: "Base", currency: "ETH", base: "eth" },
    // { chain_id: 1800, name: "Bitcoin", currency: "BTC", base: "btc" },
]

export const coins = [
    { name: "USDT", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/USDT?_a=DATAdtAAZAA0", networks: [1, 56, 137, 900, 1000] },
    // { name: "BTC", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/BTC?_a=DATAdtAAZAA0" },
    { name: "ETH", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/ETH?_a=DATAdtAAZAA0", networks: [1] },
    // { name: "LTC", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/LTC?_a=DATAdtAAZAA0" },
    // { name: "TRON", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/TRON?_a=DATAdtAAZAA0" },
    { name: "USDC", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/USDC?_a=DATAdtAAZAA0", networks: [1, 56, 137, 900, 1000] },
    // { name: "XRP", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/XRP?_a=DATAdtAAZAA0" },
    { name: "BNB", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/BNB?_a=DATAdtAAZAA0", networks: [56] },
    // { name: "DOGE", logo: "https://res.cloudinary.com/betengine/image/upload/q_auto/f_webp/v1/media-cloudbet/wallet/currency-icons/DOGE?_a=DATAdtAAZAA0" },
]